import { Resend } from "resend";

export class EmailService {
    private resend: Resend | null;

    constructor() {
        const apiKey = process.env.RESEND_API_KEY?.trim();
        this.resend = apiKey ? new Resend(apiKey) : null;
        if (!this.resend) {
            console.warn("RESEND_API_KEY not set; email delivery will be skipped.");
        }
    }

    async sendBriefEmail(to: string, briefText: string, date: string) {
        if (!this.resend) {
            console.warn("RESEND_API_KEY not set, skipping email");
            return null;
        }

        const { data, error } = await this.resend.emails.send({
            from: "Morning Brief <brief@resend.dev>", // Use your verified domain in production
            to: [to],
            subject: `Your Morning Brief - ${date}`,
            html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #4f46e5; font-size: 24px;">☀️ Your Morning Brief</h1>
          <p style="color: #666; font-size: 14px;">${date}</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          <div style="white-space: pre-wrap; line-height: 1.7; color: #333; font-size: 16px;">
${briefText}
          </div>
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="color: #999; font-size: 12px;">
            Generated by Morning Brief • <a href="${process.env.BETTER_AUTH_URL || 'http://localhost:3000'}">Open App</a>
          </p>
        </div>
      `,
        });

        if (error) {
            console.error("Failed to send email:", error);
            throw new Error(`Email send failed: ${error.message}`);
        }

        console.log("Email sent successfully:", data?.id);
        return data;
    }
}

export const emailService = new EmailService();
